export const employeeColumns = [{
        fieldName: "EmployeeCode",
        displayName: "MÃ NHÂN VIÊN",
        formatType: "",
        width: "min-width: 140px;",
        style: "text-align: left",
    },
    {
        fieldName: "EmployeeName",
        displayName: "TÊN NHÂN VIÊN",
        formatType: "",
        width: "min-width: 250px;",
        style: "text-align: left",
    },
    {
        fieldName: "Gender",
        displayName: "GIỚI TÍNH",
        formatType: "gender",
        width: "min-width: 110px;",
        style: "text-align: left",
    },
    {
        fieldName: "DateOfBirth",
        displayName: "NGÀY SINH",
        formatType: "ddmmyyyy",
        width: "min-width: 150px;",
        style: "text-align: center",
    },
    {
        fieldName: "IdentityNumber",
        displayName: "SỐ CMND",
        formatType: "",
        width: "min-width: 160px;",
        style: "text-align: left",
    },
    {
        fieldName: "EmployeePosition",
        displayName: "CHỨC DANH",
        formatType: "",
        width: "min-width: 200px;",
        style: "text-align: left; min-width: 200px;",
    },
    {
        fieldName: "DepartmentName",
        displayName: "TÊN ĐƠN VỊ",
        formatType: "",
        width: "min-width: 200px;",
        style: "text-align: left",
    },
    {
        fieldName: "PhoneNumber",
        displayName: "DT DI ĐỘNG",
        formatType: "",
        width: "min-width: 140px;",
        style: "text-align: left",
    },
    {
        fieldName: "TelephoneNumber",
        displayName: "ĐT cố định",
        formatType: "",
        width: "min-width: 140px;",
        style: "text-align: left",
    },
    {
        fieldName: "Email",
        displayName: "EMAIL",
        formatType: "",
        width: "min-width: 200px;",
        style: "text-align: left",
    },
    {
        fieldName: "BankAccountNumber",
        displayName: "SỐ TÀI KHOẢN",
        formatType: "",
        width: "min-width: 150px;",
        style: "text-align: left",
    },
    {
        fieldName: "BankName",
        displayName: "TÊN NGÂN HÀNG",
        formatType: "",
        width: "min-width: 200px;",
        style: "text-align: left",
    },
    {
        fieldName: "BankBranchName",
        displayName: "CHI NHÁNH TK NGÂN HÀNG",
        formatType: "",
        width: "min-width: 200px;",
        style: "text-align: left; ",
    },
];