export const employeeColumns = [{
        fieldName: "employeeCode",
        displayName: "MÃ NHÂN VIÊN",
        formatType: "",
        width: "min-width: 140px;",
        style: "text-align: left",
    },
    {
        fieldName: "fullName",
        displayName: "TÊN NHÂN VIÊN",
        formatType: "",
        width: "min-width: 250px;",
        style: "text-align: left",
    },
    {
        fieldName: "gender",
        displayName: "GIỚI TÍNH",
        formatType: "gender",
        width: "min-width: 110px;",
        style: "text-align: left",
    },
    {
        fieldName: "dateOfBirth",
        displayName: "NGÀY SINH",
        formatType: "ddmmyyyy",
        width: "min-width: 150px;",
        style: "text-align: center",
    },
    {
        fieldName: "identityNumber",
        displayName: "SỐ CMND",
        formatType: "",
        width: "min-width: 160px;",
        style: "text-align: left",
    },
    {
        fieldName: "identityDate",
        displayName: "NGÀY CẤP",
        formatType: "ddmmyyyy",
        width: "min-width: 150px;",
        style: "text-align: center",
    },
    {
        fieldName: "identityPlace",
        displayName: "NƠI CẤP",
        formatType: "",
        width: "min-width: 160px;",
        style: "text-align: left",
    },
    {
        fieldName: "positionName",
        displayName: "CHỨC DANH",
        formatType: "",
        width: "min-width: 200px;",
        style: "text-align: left; min-width: 200px;",
    },
    {
        fieldName: "departmentName",
        displayName: "TÊN ĐƠN VỊ",
        formatType: "departmentName",
        width: "min-width: 200px;",
        style: "text-align: left",
    },
    {
        fieldName: "phoneNumber",
        displayName: "DT DI ĐỘNG",
        formatType: "",
        width: "min-width: 140px;",
        style: "text-align: left",
    },
    {
        fieldName: "telephoneNumber",
        displayName: "ĐT cố định",
        formatType: "",
        width: "min-width: 140px;",
        style: "text-align: left",
    },
    {
        fieldName: "email",
        displayName: "EMAIL",
        formatType: "",
        width: "min-width: 200px;",
        style: "text-align: left",
    },
    {
        fieldName: "bankAccountNumber",
        displayName: "SỐ TÀI KHOẢN",
        formatType: "",
        width: "min-width: 150px;",
        style: "text-align: left",
    },
    {
        fieldName: "bankName",
        displayName: "TÊN NGÂN HÀNG",
        formatType: "",
        width: "min-width: 200px;",
        style: "text-align: left",
    },
    {
        fieldName: "bankBranchName",
        displayName: "CHI NHÁNH TK NGÂN HÀNG",
        formatType: "",
        width: "min-width: 200px;",
        style: "text-align: left; ",
    },
];